"""empty message

Revision ID: 262ad86dd43f
Revises: 1c45665daef6
Create Date: 2024-08-06 19:53:55.876542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262ad86dd43f'
down_revision = '1c45665daef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=230), nullable=True),
    sa.Column('email', sa.String(length=230), nullable=True),
    sa.Column('password', sa.String(length=230), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
